export const ADD_CITY = "ADD_CITY";
export const ADD_WEATHER = "ADD_WEATHER";
export const SET_FILTER = "SET_FILTER";
export const DELETE_TRACKED_CITY = "DELETE_TRACKED_CITY";
export const DELETE_TRACKED_WEATHER = "DELETE_TRACKED_WEATHER";